// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkohjcpqmcwfxtfkkrma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprb2hqY3BxbWN3Znh0Zmtrcm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTY0MzIsImV4cCI6MjA3NDE5MjQzMn0.Lm19SHIIOL5EFs7zopfNvZLOuC_T5atn3_eyG5-_MFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});